' Projections sample — demonstrates on-the-fly coordinate system reprojection
' of map layers without reloading data (ActiveX/COM edition — VB.NET host).
'
' What the sample shows:
'   - Loading a world map (vector layer) into the GIS viewer
'   - Accessing the projection catalogue via GisUtils.CSProjList (COM instance)
'   - Creating/building custom coordinate systems via COM constructors
'   - Switching the viewer's coordinate system via GIS.CS property
'   - On-the-fly reprojection: all layers instantly reproject in memory
'   - No data reload required — reprojection is automatic and seamless
'   - Switching between different projection types (Mercator, UTM, etc.)
'   - Combo box selector for choosing projection from the full catalogue
'   - Real-time map updates reflecting the new projection
'
' ActiveX/COM-specific details:
'   - GisUtils accessed as TGIS_Utils instance (COM object, not static)
'   - Open exposed as Open_2 to avoid COM naming conflicts
'   - TGIS_CSProjectedCoordinateSystem requires New + Create_() initialization
'   - AxTGIS_ViewerWnd is the ActiveX wrapper control
'
' Demonstrates how TatukGIS XDK supports on-the-fly coordinate reprojection
' for map display when the viewer is hosted as an ActiveX control in a
' .NET WinForms application.
'
' Key concepts covered:
'   GisUtils.CSProjList (TGIS_Utils instance)
'       The projection catalogue accessed through a TGIS_Utils COM object.
'       In the ActiveX edition, utility objects such as coordinate-system
'       registries are accessed as instance members of TGIS_Utils rather than
'       as static/shared members, because COM does not support shared methods.
'
'   TGIS_CSProjectedCoordinateSystem  (COM class)
'       A projected CRS assembled at runtime from a geographic datum, a linear
'       unit, and a projection method.  In the COM edition the constructor is
'       separate: first create the object with New, then call Create_() to
'       initialise it with the component EPSGs and default parameters.
'       EPSG = -1 marks it as a user-defined (temporary) CRS.
'
'   TGIS_CSGeographicCoordinateSystem (EPSG 4030)
'       WGS 84 unscaled — used as the geographic datum base for any projected
'       CRS independent of the specific projection.
'
'   AxTGIS_ViewerWnd  (ActiveX wrapper)
'       The ActiveX-hosted viewer control.  The API mirrors the NDK managed
'       control but is accessed through the COM interop wrapper generated by
'       the Ax* prefix classes.  Open is exposed as Open_2 (with the bool
'       overload) to avoid a COM naming conflict.
'
'   GIS.CS property
'       Assigning a new CRS triggers on-the-fly reprojection of every loaded
'       layer without reloading or modifying source data.
'
'   GIS.FullExtent()
'       Zooms to the combined extent of all layers in the current CRS.
'
' Workflow:
'   1. WinForm_Load enumerates standard projections from GisUtils.CSProjList
'      into a sorted combo box, then opens the bundled world map project.
'   2. cbxSrcProjection_SelectedIndexChanged builds a projected CRS from the
'      chosen projection and assigns it to the viewer for on-the-fly reprojection.
' =============================================================================

Imports Microsoft.VisualBasic
Imports System
Imports System.Drawing
Imports System.Collections
Imports System.ComponentModel
Imports System.Windows.Forms
Imports System.Data
Imports TatukGIS_XDK11

Namespace Projections
    ''' <summary>
    ''' Main application form for the Projections sample (ActiveX edition).
    ''' Shows a world map that is immediately reprojected whenever the user
    ''' picks a different projection method from the combo box.
    ''' </summary>
    Public Class WinForm
        Inherits System.Windows.Forms.Form

        ''' <summary>Required designer variable.</summary>
        Private components As System.ComponentModel.Container = Nothing

        ''' <summary>Drop-down list of available projection names (WKT strings).</summary>
        Private WithEvents cbxSrcProjection As System.Windows.Forms.ComboBox

        ''' <summary>
        ''' ActiveX-hosted TatukGIS viewer control.
        ''' The AxTGIS_ViewerWnd wrapper exposes the COM XDK viewer via .NET interop.
        ''' </summary>
        Private GIS As AxTatukGIS_XDK11.AxTGIS_ViewerWnd

        ''' <summary>Top toolbar panel that hosts the projection combo box.</summary>
        Private panel1 As System.Windows.Forms.Panel

        ''' <summary>
        ''' Initialises the form and its designer-generated child controls.
        ''' </summary>
        Public Sub New()
            '
            ' Required for Windows Form Designer support
            '
            InitializeComponent()

            '
            ' TODO: Add any constructor code after InitializeComponent call
            '
        End Sub

        ''' <summary>
        ''' Clean up any resources being used.
        ''' </summary>
        Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
            If disposing Then
                If Not components Is Nothing Then
                    components.Dispose()
                End If
            End If
            MyBase.Dispose(disposing)
        End Sub

#Region "Windows Form Designer generated code"
        ''' <summary>
        ''' Required method for Designer support - do not modify
        ''' the contents of this method with the code editor.
        ''' </summary>
        Private Sub InitializeComponent()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(WinForm))
            Me.cbxSrcProjection = New System.Windows.Forms.ComboBox()
            Me.panel1 = New System.Windows.Forms.Panel()
            Me.GIS = New AxTatukGIS_XDK11.AxTGIS_ViewerWnd()
            Me.panel1.SuspendLayout()
            CType(Me.GIS, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'cbxSrcProjection
            '
            Me.cbxSrcProjection.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
            Me.cbxSrcProjection.Location = New System.Drawing.Point(0, 4)
            Me.cbxSrcProjection.Name = "cbxSrcProjection"
            Me.cbxSrcProjection.Size = New System.Drawing.Size(193, 21)
            Me.cbxSrcProjection.TabIndex = 0
            '
            'panel1
            '
            Me.panel1.Controls.Add(Me.cbxSrcProjection)
            Me.panel1.Dock = System.Windows.Forms.DockStyle.Top
            Me.panel1.Location = New System.Drawing.Point(0, 0)
            Me.panel1.Name = "panel1"
            Me.panel1.Size = New System.Drawing.Size(584, 29)
            Me.panel1.TabIndex = 2
            '
            'GIS
            '
            Me.GIS.Dock = System.Windows.Forms.DockStyle.Fill
            Me.GIS.Enabled = True
            Me.GIS.Location = New System.Drawing.Point(0, 29)
            Me.GIS.Name = "GIS"
            Me.GIS.OcxState = CType(resources.GetObject("GIS.OcxState"), System.Windows.Forms.AxHost.State)
            Me.GIS.Size = New System.Drawing.Size(584, 437)
            Me.GIS.TabIndex = 1
            '
            'WinForm
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(96.0!, 96.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi
            Me.ClientSize = New System.Drawing.Size(584, 466)
            Me.Controls.Add(Me.GIS)
            Me.Controls.Add(Me.panel1)
            Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
            Me.Location = New System.Drawing.Point(200, 120)
            Me.Name = "WinForm"
            Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
            Me.Text = "TatukGIS Samples - Projections"
            Me.panel1.ResumeLayout(False)
            CType(Me.GIS, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub
#End Region

        ' TGIS_Utils instance used throughout the form to access coordinate-system
        ' catalogues.  In the ActiveX/COM edition all utility APIs are accessed
        ' as instance methods rather than shared/static members.
        Dim GisUtils As New TGIS_Utils()

        ''' <summary>
        ''' Application entry point.  Initialises the Windows Forms runtime and
        ''' launches the main form.
        ''' </summary>
        <STAThread>
        Shared Sub Main()
            Application.EnableVisualStyles()
            Application.SetCompatibleTextRenderingDefault(False)
            Application.Run(New WinForm())
        End Sub

        ' ---------------------------------------------------------------------
        '  WinForm_Load
        ' ---------------------------------------------------------------------
        ' Called once when the form finishes loading.
        '
        ' Responsibilities:
        '   1. Enumerate every "standard" projection in the TatukGIS catalogue
        '      via GisUtils.CSProjList.  In the COM edition, projection entries
        '      are accessed via the Projection(index) accessor rather than the
        '      array-index syntax used in the NDK managed API.
        '   2. Collect WKT names into a SortedList for alphabetical display,
        '      then populate the combo box.
        '   3. Open the bundled world map project via Open_2 (the two-argument
        '      overload that accepts a path and a bool) — COM naming disambiguation.
        '   4. Select the first projection to trigger the initial CRS assignment.
        ' ---------------------------------------------------------------------
        Private Sub WinForm_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles MyBase.Load
            Dim i As Int32
            Dim lst As SortedList

            ' Collect standard projection WKT names into a sorted list so the
            ' combo box displays them in alphabetical order.
            lst = New System.Collections.SortedList()
            lst.Clear()

            For i = 0 To GisUtils.CSProjList.Count() - 1
                ' IsStandard filters out partial or experimental projection
                ' entries that are not suitable for general use.
                ' Note: COM edition uses .Projection(i) instead of [i] indexer.
                If (GisUtils.CSProjList.Projection(i).IsStandard) Then
                    ' WKT is the Well-Known Text identifier — used both as the
                    ' display string and as the key for later catalogue lookup.
                    lst.Add(GisUtils.CSProjList.Projection(i).WKT, GisUtils.CSProjList.Projection(i).WKT)
                End If
            Next
            For i = 0 To lst.Count - 1
                cbxSrcProjection.Items.Add(lst.GetByIndex(i))
            Next

            ' Open_2 is the COM-disambiguated name for the two-argument Open overload.
            ' The second argument (True) enables the full-extent zoom after opening.
            GIS.Open_2(GisUtils.GisSamplesDataDirDownload() & "\Samples\Projects\world.ttkproject", True)

            ' Selecting index 0 triggers cbxSrcProjection_SelectedIndexChanged,
            ' which builds and assigns the first CRS to the viewer.
            cbxSrcProjection.SelectedIndex = 0
        End Sub

        ' ---------------------------------------------------------------------
        '  cbxSrcProjection_SelectedIndexChanged
        ' ---------------------------------------------------------------------
        ' Called whenever the user selects a different projection in the combo.
        '
        ' Core on-the-fly reprojection pattern (COM / ActiveX edition):
        '   1. Resolve the chosen projection method by WKT from GisUtils.CSProjList.
        '   2. Combine it with a geographic datum (EPSG 4030 = WGS 84 unscaled)
        '      and a linear unit (Metre) to form a TGIS_CSProjectedCoordinateSystem.
        '      In the COM edition, the CRS is first instantiated with New, then
        '      initialised via Create_() because COM constructors cannot accept
        '      arguments directly.
        '   3. Assign the new CRS to GIS.CS.  The viewer reprojects all loaded
        '      layers in memory; no source files are modified.
        '   4. Call FullExtent() to re-zoom to the world extent in the new CRS.
        '
        ' Lock/Unlock prevents intermediate repaints, eliminating flicker.
        ' The inner Try/Catch is intentional: some projections cannot represent
        ' the full global extent and will throw; the viewer stays in its last
        ' valid state when this occurs.
        ' ---------------------------------------------------------------------
        Private Sub cbxSrcProjection_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles cbxSrcProjection.SelectedIndexChanged
            Dim sproj As String
            Dim ogcs As TGIS_CSGeographicCoordinateSystem
            Dim ounit As TGIS_CSUnits
            Dim oproj As TGIS_CSProjAbstract
            Dim ocs As TGIS_CSCoordinateSystem

            ' Retrieve the WKT name selected by the user.
            sproj = CType(cbxSrcProjection.Items(cbxSrcProjection.SelectedIndex), String)

            ' WGS 84 unscaled — the standard geographic datum base for on-the-fly
            ' CRS construction without committing to a specific ellipsoid scaling.
            ogcs = GisUtils.CSGeographicCoordinateSystemList.ByEPSG(4030)

            ' Metre — the most common linear unit for projected coordinate systems.
            ounit = GisUtils.CSUnitsList.ByWKT("METER")

            ' Look up the projection method object from the global catalogue.
            oproj = GisUtils.CSProjList.ByWKT(sproj)

            ' Build a complete projected CRS using the two-step COM pattern:
            '   New  — allocates the COM object.
            '   Create_ — initialises it with component EPSGs and default params.
            ' EPSG = -1 : user-defined, not registered in the EPSG database.
            ' "Test"    : temporary display name for this CRS.
            ' DefaultParams provides canonical values (central meridian, standard
            ' parallels, etc.) so no manual parameter entry is required.
            ocs = New TGIS_CSProjectedCoordinateSystem()
            ocs.Create_(-1, "Test", ogcs.EPSG, ounit.EPSG, oproj.EPSG,
                                                       GisUtils.CSProjectedCoordinateSystemList.DefaultParams(oproj.EPSG))

            ' Lock prevents repaints during the combined CS + extent update.
            GIS.Lock()
            Try
                Try
                    ' Assigning CS triggers on-the-fly reprojection of all layers.
                    GIS.CS = ocs

                    ' Re-zoom to the full world extent expressed in the new CRS.
                    GIS.FullExtent()
                Catch
                    ' Some projection methods cannot represent the global extent.
                    ' Silently ignore to leave the viewer in its last valid state.
                End Try
            Finally
                GIS.Unlock()
            End Try
        End Sub
    End Class
End Namespace
